### ISSUE TITLE
1.9-1.6.0.40 crashes dedicated forge server 1.9 build 1821 on startup

### ISSUE THREAD

**Issue by kreezxil** [Lunatrius/Stackie#7]
Issue: stackie-1.9-1.6.0.40 crashes dedicated forge server 1.9 build 1821 on startup

crash report:
https://gist.github.com/252ab3e299481a4a33ef5d1ad595f098

fml server latest:
https://gist.github.com/59f5ab2bb2c30a0399fdb431f572bdd8

**Comment by Lunatrius** [comment]
Could you test whether it happens when you have only Stackie installed? And if it does happen, could you check whether it happens on Forge 1811?

**Comment by kreezxil** [comment]
It's stable on 1816

-----Original Message-----

**Comment by Lunatrius** [comment]
And 1817 doesn't work anymore? That would be strange because nothing changed in the registry code in that version.

You may have to keep using the latest version on which it works until Forge stabilizes. It's in an early "beta" stage and a lot of things are considered unstable, some things are getting removed without any sort of warning because of that.

I'll still make sure to check whether the compiled code differs between 1811 and 1824 (currently the latest available).

**Comment by kreezxil** [comment]
There're the new versions of forge in the last two hours. I'll try again after it all slows down

-----Original Message-----

**Comment by kreezxil** [comment]
It's crept back up again with Forge build 1863

Issue: stackie-1.9-1.6.0.40 crashes dedicated forge server 1.9 build 1863 on startup

crash report:
https://gist.github.com/97aa2a9a810ec360e5df4b5bdab1aec1

fml server latest:
https://gist.github.com/b44d9aacee2ca2d250fa789dd0856b33

**Comment by Lunatrius** [comment]
Fixed in `1.6.0.41`.
